version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payplaner_frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:3000}
      REACT_APP_TELEGRAM_BOT_NAME: ${REACT_APP_TELEGRAM_BOT_NAME}
    ports:
      - "3001:3001"
    restart: unless-stopped

